site_name: dash-database-visualizer
nav:
    - Home: "README.md"
    - Implementation : "Implementation.md"
    - About: about.md
    
theme: 
    name: mkdocs
    nav_style: dark
    palette:
        scheme: default
    features:
        - navigation.tabs
